import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teste Env</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Inicio console! 1.10!</h2>

        <h4>ENV AQUI {process.env.NEXT_PUBLIC_TESTE}</h4>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
